### ISSUE TITLE
K3,lean固件，openclash不成功

### ISSUE THREAD

**Issue by wclmgcd** [hansyao/breakwall#1]
按照大佬的步骤，运行./cf-auto-passwall.sh  时，
等待测速进程结束,筛选出三个优选的IP
测速完成
指向解析获取CF节点IP
-=O#- # # #
正在测试 ICMP 丢包率:进程数 1,已完成 0 %
正在测试 ICMP 丢包率:进程数 2,已完成 1 %

一直这样循环下去，
提示OpenClash Already Stop!时，OpenClash的守护程序停止，

还有我的节点有机场订阅的，也有自建的，配置文件也是自己修改的，可以指定修改OpenClash的设置文件中的自建的ip项吗，就像passwall一样

**Comment by hansyao** [comment]
原来的代码太冗长了，这两天刚重构了下代码，有空传上来你可以试试看。自建ip项功能没有实现

**Comment by hansyao** [comment]
> 按照大佬的步骤，运行./cf-auto-passwall.sh 时，
> 等待测速进程结束,筛选出三个优选的IP
> 测速完成
> 指向解析获取CF节点IP
> -=O#- # # #
> 正在测试 ICMP 丢包率:进程数 1,已完成 0 %
> 正在测试 ICMP 丢包率:进程数 2,已完成 1 %
> 
> 一直这样循环下去，
> 提示OpenClash Already Stop!时，OpenClash的守护程序停止，
> 
> 还有我的节点有机场订阅的，也有自建的，配置文件也是自己修改的，可以指定修改OpenClash的设置文件中的自建的ip项吗，就像passwall一样

原来版本的openclash是没有做测试的，只为梅林固件做的，你需要用的话得自己解决bug

**Comment by hansyao** [comment]
> 原来的代码太冗长了，这两天刚重构了下代码，有空传上来你可以试试看。自建ip项功能没有实现

需要同时用其他代理配置的话最简单的办法自己用subconverter进行合并转一下即可

**Comment by hansyao** [comment]
全新重构版的代码刚上传了，现在设置没这么复杂，基本傻瓜式操作，你可以试试看
