### ISSUE TITLE
执行错误，

### ISSUE THREAD

**Issue by wclmgcd** [hansyao/breakwall#2]
./cf_speedtest.sh: line 145: syntax error: unexpected "done" (expecting "}")

**Comment by hansyao** [comment]
你是什么平台？我这里openwrt, merlin, 本机测试都没有问题

**Comment by wclmgcd** [comment]
openwrt，lean ，K3  内核5.4.143

**Comment by hansyao** [comment]
你在代码前面加一行参数```set -x```, 运行后把完整日志贴上来看看,（注意贴上来前删掉掉你自己的私密信息)
```bash
#!/bin/sh

set -x

```

**Comment by hansyao** [comment]
> openwrt，lean ，K3  内核5.4.143

我估计你的openwrt是没有安装uci命令，这个脚本修改passwall设置需要依赖uci工具，你先查看一下，终端输入 ```which uci``` 看找不找得到，没有的话你得先安装一下

**Comment by hansyao** [comment]
> > openwrt，lean ，K3  内核5.4.143
> 
> 我估计你的openwrt是没有安装uci命令，这个脚本修改passwall设置需要依赖uci工具，你先查看一下，终端输入 `which uci` 看找不找得到，没有的话你得先安装一下

更新了下增加了passwall的uci依赖检查，如果是这个问题你可以测试一下

**Comment by wclmgcd** [comment]
root@OpenWrt:~# ./cf_speedtest.sh
+ PLATFORM=
+ PING_COUNT=100
+ TARGET_IPS=10
+ SCHEDULE='30 */6 * * *'
+ GHPROXY=https://ghproxy.com/
+ PREF_INI_URL=https://ghproxy.com/https://gist.githubusercontent.com/hansyao/e00678003f4eea63b219217638582414/raw/cloudflare.ini
+ PREF_INI=/tmp/cloudflare.ini
+ POOL=/tmp/clash_cloudflare.yaml
+ CLASH_CONFIG=/tmp/clash_cloudflare_final.yaml
+ WWW_PATH=/var/www/html/
+ CLASH_ENABLE=yes
+ PASSWALL_ENABLE=yes
+ SPEED_TEST=yes
+ GIST_TOKEN=
+ GIST_ID=
+ REMOTE_NAME=clash_cloudflare.yaml
+ DESC_JSON=/tmp/gist.json
+ RESPONSE=/tmp/gist_response.json
./cf_speedtest.sh: line 145: syntax error: unexpected "done" (expecting "}")

**Comment by wclmgcd** [comment]
最新的提示
root@OpenWrt:~#  ./cf_speedtest.sh
./cf_speedtest.sh: line 272: syntax error: unexpected "}" (expecting "fi")
root@OpenWrt:~#  ./cf_speedtest.sh
./cf_speedtest.sh: line 272: syntax error: unexpected "}" (expecting "fi")

**Comment by wclmgcd** [comment]
第一个是老版本的

**Comment by hansyao** [comment]
你的把```set -x```后把完整日志贴上来，这个日志是看不出问题的

**Comment by hansyao** [comment]
另外openwrt运行命令应该是带参数运行
```bash
./cf_speedtest.sh openwrt
```

**Comment by wclmgcd** [comment]
root@OpenWrt:~# ./cf_speedtest.sh openwrt
+ PLATFORM=openwrt
+ PING_COUNT=100
+ TARGET_IPS=10
+ SCHEDULE='30 */6 * * *'
+ GHPROXY=https://ghproxy.com/
+ PREF_INI_URL=https://ghproxy.com/https://gist.githubusercontent.com/hansyao/e00678003f4eea63b219217638582414/raw/cloudflare.ini
+ TMP_DIR=/tmp/mytemp
+ PREF_INI=/tmp/mytemp/cloudflare.ini
+ POOL=/tmp/mytemp/main_cloudflare.yaml
+ CLASH_CONFIG=/tmp/mytemp/clash_cloudflare_final.yaml
+ WWW_PATH=/var/www/html/
+ CLASH_ENABLE=yes
+ PASSWALL_ENABLE=yes
+ SPEED_TEST=yes
+ CONVERTER_ENABLE=yes
+ GIST_TOKEN=
+ REMOTE_NAME=cloudflare
+ CONVERT_clash=yes
+ CONVERT_clashr=yes
+ CONVERT_quan=yes
+ CONVERT_quanx=yes
+ CONVERT_loon=yes
+ CONVERT_mellow=yes
+ CONVERT_surfboard=yes
+ CONVERT_surge2=yes
+ CONVERT_surge3=yes
+ CONVERT_surge4=yes
+ CONVERT_v2ray=yes
+ CONVERT_mixed=yes
+ DESC_JSON=/tmp/mytemp/gist.json
+ RESPONSE=/tmp/mytemp/gist_response.json
+ GIST_ID_main=
+ GIST_ID_clash=
+ GIST_ID_clashr=
+ GIST_ID_quan=
+ GIST_ID_quanx=
+ GIST_ID_loon=
+ GIST_ID_mellow=
+ GIST_ID_surfboard=
+ GIST_ID_surge2=
+ GIST_ID_surge3=
+ GIST_ID_surge4=
+ GIST_ID_v2ray=
+ GIST_ID_mixed=
./cf_speedtest.sh: line 272: syntax error: unexpected "}" (expecting "fi")

**Comment by hansyao** [comment]
> root@OpenWrt:~# ./cf_speedtest.sh
> 
> * PLATFORM=
> * PING_COUNT=100
> * TARGET_IPS=10
> * SCHEDULE='30 */6 * * *'
> * GHPROXY=https://ghproxy.com/
> * PREF_INI_URL=https://ghproxy.com/https://gist.githubusercontent.com/hansyao/e00678003f4eea63b219217638582414/raw/cloudflare.ini
> * PREF_INI=/tmp/cloudflare.ini
> * POOL=/tmp/clash_cloudflare.yaml
> * CLASH_CONFIG=/tmp/clash_cloudflare_final.yaml
> * WWW_PATH=/var/www/html/
> * CLASH_ENABLE=yes
> * PASSWALL_ENABLE=yes
> * SPEED_TEST=yes
> * GIST_TOKEN=
> * GIST_ID=
> * REMOTE_NAME=clash_cloudflare.yaml
> * DESC_JSON=/tmp/gist.json
> * RESPONSE=/tmp/gist_response.json
>   ./cf_speedtest.sh: line 145: syntax error: unexpected "done" (expecting "}")

这个PLATFORM你不能动它的，这个是传入参数变量，留空肯定会出错的 
```bash
PLATFORM=$1
```

**Comment by wclmgcd** [comment]
#!/bin/sh
set -x
PLATFORM=$1	#鍙€夊钩鍙帮細 merlin, openwrt, vps

# 涓€鑸厤缃父閲忥紝 鍙寜闇€鏇存敼
PING_COUNT=100	#鍗曚釜ping妫€娴嬫鏁? 缂虹渷100娆?
TARGET_IPS=10	#鐩爣IP鏁?缂虹渷20锛屽崟涓€浠ｇ悊20涓狢DN IP瓒冲, 澶浜嗕篃娌℃剰涔?
SCHEDULE="30 */6 * * *"	#璁″垝浠诲姟 (鐢变簬crontab鐗堟湰涓嶅悓锛屽悇涓钩鍙拌鍒掍换鍔＄殑鏍煎紡鍙兘浼氱◢鏈夊樊寮傦紝鎸夊疄闄呮儏鍐靛～鍐?
GHPROXY='https://ghproxy.com/'				#github浠ｇ悊缃戝潃
PREF_INI_URL="${GHPROXY}https://gist.githubusercontent.com/hansyao/e00678003f4eea63b219217638582414/raw/cloudflare.ini"	#杩滅▼瑙勫垯鏂囦欢
TMP_DIR='/tmp/mytemp'					#涓存椂鏂囦欢璺緞
PREF_INI="${TMP_DIR}/cloudflare.ini"			#鏈湴瑙勫垯鏂囦欢锛屽PREF_INI_URL鏈畾涔夛紝鍒欐姄鍙朠REF_INI鏈湴瑙勫垯
POOL="${TMP_DIR}/main_cloudflare.yaml"			#鑴氭湰鑷姩鐢熸垚鐨勮浆鎹㈣鍒欏墠鐨勪唬鐞嗘睜鏂囦欢璺緞
CLASH_CONFIG="${TMP_DIR}/clash_cloudflare_final.yaml"	#鑴氭湰鑷姩瑙勫垯杞崲鍚庣殑鐨勪唬鐞嗘睜鏂囦欢璺緞
WWW_PATH='/var/www/html/'				#VPS鏈嶅姟鍣ㄤ笂鐨剋eb璺緞锛屽闇€瑕佸缃戣闂渶瑕佸皢鍏惰矾寰勫～鍐欏湪杩欓噷
CLASH_ENABLE=yes					#鏄惁搴旂敤clash(yes/no), 濉玭o涓嶈繘琛岃鍒欒浆鎹? opewrt濉玭o鍚屾椂涓嶅簲鐢ㄥ埌閰嶇疆鏂囦欢
PASSWALL_ENABLE=yes					#鏄惁搴旂敤passwall(yes/no), openwrt閫傜敤锛屽～no涓嶇敤passwall
SPEED_TEST=yes						#鏄惁鍚敤甯﹀娴嬮€?yes/no), 甯﹀娴嬮€熻€楁椂杈冮暱锛屽彲浠ュ厛娴嬭瘯涓嬪惎鐢ㄥ悗鐨勬晥鏋滃樊寮傦紝宸紓涓嶅ぇ寤鸿涓嶅惎鐢?
CONVERTER_ENABLE=yes					#鏄惁杩涜瑙勫垯杞崲骞剁敓鎴愯闃呴摼鎺?蹇呴』寮€鍚痝ist)
GIST_TOKEN=	#github瀵嗛挜锛岄渶瑕佹巿浜坓ist鏉冮檺锛屽涓嶄笂浼犵暀绌哄嵆鍙?
REMOTE_NAME='cloudflare'

**Comment by wclmgcd** [comment]
没动

**Comment by hansyao** [comment]
> 没动

你的日志不完全，没有定位到是哪个变量的错误。

**Comment by hansyao** [comment]
> #!/bin/sh
> set -x
> PLATFORM=$1 #鍙€夊钩鍙帮細 merlin, openwrt, vps
> 
> # 涓€鑸厤缃父閲忥紝 鍙寜闇€鏇存敼
> PING_COUNT=100 #鍗曚釜ping妫€娴嬫鏁? 缂虹渷100娆?
> TARGET_IPS=10 #鐩爣IP鏁?缂虹渷20锛屽崟涓€浠ｇ悊20涓狢DN IP瓒冲, 澶浜嗕篃娌℃剰涔?
> SCHEDULE="30 */6 * * *" #璁″垝浠诲姟 (鐢变簬crontab鐗堟湰涓嶅悓锛屽悇涓钩鍙拌鍒掍换鍔＄殑鏍煎紡鍙兘浼氱◢鏈夊樊寮傦紝鎸夊疄闄呮儏鍐靛～鍐?
> GHPROXY='https://ghproxy.com/' #github浠ｇ悊缃戝潃
> PREF_INI_URL="${GHPROXY}https://gist.githubusercontent.com/hansyao/e00678003f4eea63b219217638582414/raw/cloudflare.ini" #杩滅▼瑙勫垯鏂囦欢
> TMP_DIR='/tmp/mytemp' #涓存椂鏂囦欢璺緞
> PREF_INI="${TMP_DIR}/cloudflare.ini" #鏈湴瑙勫垯鏂囦欢锛屽PREF_INI_URL鏈畾涔夛紝鍒欐姄鍙朠REF_INI鏈湴瑙勫垯
> POOL="${TMP_DIR}/main_cloudflare.yaml" #鑴氭湰鑷姩鐢熸垚鐨勮浆鎹㈣鍒欏墠鐨勪唬鐞嗘睜鏂囦欢璺緞
> CLASH_CONFIG="${TMP_DIR}/clash_cloudflare_final.yaml" #鑴氭湰鑷姩瑙勫垯杞崲鍚庣殑鐨勪唬鐞嗘睜鏂囦欢璺緞
> WWW_PATH='/var/www/html/' #VPS鏈嶅姟鍣ㄤ笂鐨剋eb璺緞锛屽闇€瑕佸缃戣闂渶瑕佸皢鍏惰矾寰勫～鍐欏湪杩欓噷
> CLASH_ENABLE=yes #鏄惁搴旂敤clash(yes/no), 濉玭o涓嶈繘琛岃鍒欒浆鎹? opewrt濉玭o鍚屾椂涓嶅簲鐢ㄥ埌閰嶇疆鏂囦欢
> PASSWALL_ENABLE=yes #鏄惁搴旂敤passwall(yes/no), openwrt閫傜敤锛屽～no涓嶇敤passwall
> SPEED_TEST=yes #鏄惁鍚敤甯﹀娴嬮€?yes/no), 甯﹀娴嬮€熻€楁椂杈冮暱锛屽彲浠ュ厛娴嬭瘯涓嬪惎鐢ㄥ悗鐨勬晥鏋滃樊寮傦紝宸紓涓嶅ぇ寤鸿涓嶅惎鐢?
> CONVERTER_ENABLE=yes #鏄惁杩涜瑙勫垯杞崲骞剁敓鎴愯闃呴摼鎺?蹇呴』寮€鍚痝ist)
> GIST_TOKEN= #github瀵嗛挜锛岄渶瑕佹巿浜坓ist鏉冮檺锛屽涓嶄笂浼犵暀绌哄嵆鍙?
> REMOTE_NAME='cloudflare'

贴上来用代码块格式方式，不然全乱掉了没法看的

**Comment by wclmgcd** [comment]
./cf_speedtest.sh: line 272: syntax error: unexpected "}" (expecting "fi")
  
最新的脚本，只是修改了59行的设置，
加set -x  还是报错如下：
root@OpenWrt:~# ./cf_speedtest.sh openwrt
+ PLATFORM=openwrt
+ PING_COUNT=100
+ TARGET_IPS=10
+ SCHEDULE='30 */6 * * *'
+ GHPROXY=https://ghproxy.com/
+ PREF_INI_URL=https://ghproxy.com/https://gist.githubusercontent.com/hansyao/e00678003f4eea63b219217638582414/raw/cloudflare.ini
+ TMP_DIR=/tmp/mytemp
+ PREF_INI=/tmp/mytemp/cloudflare.ini
+ POOL=/tmp/mytemp/main_cloudflare.yaml
+ CLASH_CONFIG=/tmp/mytemp/clash_cloudflare_final.yaml
+ WWW_PATH=/var/www/html/
+ CLASH_ENABLE=yes
+ PASSWALL_ENABLE=yes
+ SPEED_TEST=yes
+ CONVERTER_ENABLE=yes
+ GIST_TOKEN=
+ REMOTE_NAME=cloudflare
+ CONVERT_clash=yes
+ CONVERT_clashr=yes
+ CONVERT_quan=yes
+ CONVERT_quanx=yes
+ CONVERT_loon=yes
+ CONVERT_mellow=yes
+ CONVERT_surfboard=yes
+ CONVERT_surge2=yes
+ CONVERT_surge3=yes
+ CONVERT_surge4=yes
+ CONVERT_v2ray=yes
+ CONVERT_mixed=yes
+ DESC_JSON=/tmp/mytemp/gist.json
+ RESPONSE=/tmp/mytemp/gist_response.json
+ GIST_ID_main=
+ GIST_ID_clash=
+ GIST_ID_clashr=
+ GIST_ID_quan=
+ GIST_ID_quanx=
+ GIST_ID_loon=
+ GIST_ID_mellow=
+ GIST_ID_surfboard=
+ GIST_ID_surge2=
+ GIST_ID_surge3=
+ GIST_ID_surge4=
+ GIST_ID_v2ray=
+ GIST_ID_mixed=
./cf_speedtest.sh: line 272: syntax error: unexpected "}" (expecting "fi")

**Comment by hansyao** [comment]
> ./cf_speedtest.sh: line 272: syntax error: unexpected "}" (expecting "fi")
> 
>   
> 
> 最新的脚本，只是修改了59行的设置，
> 
> 加set -x  还是报错如下：
> 
> root@OpenWrt:~# ./cf_speedtest.sh openwrt
> 
> + PLATFORM=openwrt
> 
> + PING_COUNT=100
> 
> + TARGET_IPS=10
> 
> + SCHEDULE='30 */6 * * *'
> 
> + GHPROXY=https://ghproxy.com/
> 
> + PREF_INI_URL=https://ghproxy.com/https://gist.githubusercontent.com/hansyao/e00678003f4eea63b219217638582414/raw/cloudflare.ini
> 
> + TMP_DIR=/tmp/mytemp
> 
> + PREF_INI=/tmp/mytemp/cloudflare.ini
> 
> + POOL=/tmp/mytemp/main_cloudflare.yaml
> 
> + CLASH_CONFIG=/tmp/mytemp/clash_cloudflare_final.yaml
> 
> + WWW_PATH=/var/www/html/
> 
> + CLASH_ENABLE=yes
> 
> + PASSWALL_ENABLE=yes
> 
> + SPEED_TEST=yes
> 
> + CONVERTER_ENABLE=yes
> 
> + GIST_TOKEN=
> 
> + REMOTE_NAME=cloudflare
> 
> + CONVERT_clash=yes
> 
> + CONVERT_clashr=yes
> 
> + CONVERT_quan=yes
> 
> + CONVERT_quanx=yes
> 
> + CONVERT_loon=yes
> 
> + CONVERT_mellow=yes
> 
> + CONVERT_surfboard=yes
> 
> + CONVERT_surge2=yes
> 
> + CONVERT_surge3=yes
> 
> + CONVERT_surge4=yes
> 
> + CONVERT_v2ray=yes
> 
> + CONVERT_mixed=yes
> 
> + DESC_JSON=/tmp/mytemp/gist.json
> 
> + RESPONSE=/tmp/mytemp/gist_response.json
> 
> + GIST_ID_main=
> 
> + GIST_ID_clash=
> 
> + GIST_ID_clashr=
> 
> + GIST_ID_quan=
> 
> + GIST_ID_quanx=
> 
> + GIST_ID_loon=
> 
> + GIST_ID_mellow=
> 
> + GIST_ID_surfboard=
> 
> + GIST_ID_surge2=
> 
> + GIST_ID_surge3=
> 
> + GIST_ID_surge4=
> 
> + GIST_ID_v2ray=
> 
> + GIST_ID_mixed=
> 
> ./cf_speedtest.sh: line 272: syntax error: unexpected "}" (expecting "fi")
> 
> 

60行删掉没？59和60行都得改成自己的，只有一个节点留一行即可，有多个追加多行。两边的双引号必须得有

**Comment by wclmgcd** [comment]
60行删掉了还是一样的
root@OpenWrt:~#  ./cf_speedtest.sh openwrt
+ PLATFORM=openwrt
+ PING_COUNT=100
+ TARGET_IPS=10
+ SCHEDULE='30 */6 * * *'
+ GHPROXY=https://ghproxy.com/
+ PREF_INI_URL=https://ghproxy.com/https://gist.githubusercontent.com/hansyao/e00678003f4eea63b219217638582414/raw/cloudflare.ini
+ TMP_DIR=/tmp/mytemp
+ PREF_INI=/tmp/mytemp/cloudflare.ini
+ POOL=/tmp/mytemp/main_cloudflare.yaml
+ CLASH_CONFIG=/tmp/mytemp/clash_cloudflare_final.yaml
+ WWW_PATH=/var/www/html/
+ CLASH_ENABLE=yes
+ PASSWALL_ENABLE=yes
+ SPEED_TEST=yes
+ CONVERTER_ENABLE=yes
+ GIST_TOKEN=
+ REMOTE_NAME=cloudflare
+ CONVERT_clash=yes
+ CONVERT_clashr=yes
+ CONVERT_quan=yes
+ CONVERT_quanx=yes
+ CONVERT_loon=yes
+ CONVERT_mellow=yes
+ CONVERT_surfboard=yes
+ CONVERT_surge2=yes
+ CONVERT_surge3=yes
+ CONVERT_surge4=yes
+ CONVERT_v2ray=yes
+ CONVERT_mixed=yes
+ DESC_JSON=/tmp/mytemp/gist.json
+ RESPONSE=/tmp/mytemp/gist_response.json
+ GIST_ID_main=
+ GIST_ID_clash=
+ GIST_ID_clashr=
+ GIST_ID_quan=
+ GIST_ID_quanx=
+ GIST_ID_loon=
+ GIST_ID_mellow=
+ GIST_ID_surfboard=
+ GIST_ID_surge2=
+ GIST_ID_surge3=
+ GIST_ID_surge4=
+ GIST_ID_v2ray=
+ GIST_ID_mixed=
./cf_speedtest.sh: line 271: syntax error: unexpected "}" (expecting "fi")
root@OpenWrt:~# ./cf_speedtest.sh openwrt
./cf_speedtest.sh: line 271: syntax error: unexpected "}" (expecting "fi")
root@OpenWrt:~#

**Comment by hansyao** [comment]
你单独运行下这个命令看看
```
uci show passwall | grep uuid=
```

**Comment by wclmgcd** [comment]
root@OpenWrt:~# uci show passwall | grep uuid=
passwall.4ee0da30145b40788cac0c919fa66548.uuid='xxxxxxxxxxxxxxxxxxxxxxxxxf0d74f4db340'
passwall.a66ddf7a08c245eda3c2d42e702ce360.uuid='xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
passwall.bc5457a31dd84e40b92ad4ca4849065e.uuid='xxxxxxxxxxxxxxxxxxxxxxxxxf0d74f4db340'
passwall.884fe158568c4483b226dd783fae6195.uuid='xxxxxxxxxxxxxxxxxxxxxxxxxf0d74f4db340'
passwall.4db732d4acd34168b488988e257360cd.uuid='xxxxxxxxxxxxxxxxxxxxxxxxxf0d74f4db340'
passwall.ade697be318f45839a3eb38c758f2c63.uuid='xxxxxxxxxxxxxxxxxxxxxxxxxf0d74f4db340'
passwall.f4c8783b0c43469bbbf596c6672046c7.uuid='xxxxxxxxxxxxxxxxxxxxxxxxxf0d74f4db340'
passwall.1bc9116a81b14605a4e844e3549a6850.uuid='xxxxxxxxxxxxxxxxxxxxxxxxxf0d74f4db340'
passwall.6849bedac07b4eb89f2f55911d7226d5.uuid='xxxxxxxxxxxxxxxxxxxxxxxxxf0d74f4db340'
passwall.931493e32ab2417b8d900ba1d200358e.uuid='xxxxxxxxxxxxxxxxxxxxxxxxxf0d74f4db340'
passwall.6a1be8a15c964c5897c6b2222eace2b5.uuid='xxxxxxxxxxxxxxxxxxxxxxxxxf0d74f4db340'
passwall.6658db4441894d7f9d066e2bdc840cd4.uuid='xxxxxxxxxxxxxxxxxxxxxxxxxf0d74f4db340'
passwall.c4fdaa69d3ef4c88a9a20e5811489ffe.uuid='xxxxxxxxxxxxxxxxxxxxxxxxxf0d74f4db340'
passwall.d5974d34a81240de8e0f130f49a38e7b.uuid='xxxxxxxxxxxxxxxxxxxxxxxxxf0d74f4db340'
passwall.68844b8138ec40068c02d46480c28c97.uuid='xxxxxxxxxxxxxxxxxxxxxxxxxf0d74f4db340'
passwall.c909381832084d268eaa5ebc1fa773d2.uuid='xxxxxxxxxxxxxxxxxxxxxxxxxf0d74f4db340'
passwall.7b075bd813e245a29517472bb7dbc305.uuid='xxxxxxxxxxxxxxxxxxxxxxxxxf0d74f4db340'
passwall.3f416b81c3f5499facb9c99ef66522bc.uuid='xxxxxxxxxxxxxxxxxxxxxxxxxf0d74f4db340'
passwall.42ad522110284cdb8336183d5c58ad30.uuid='xxxxxxxxxxxxxxxxxxxxxxxxxf0d74f4db340'
passwall.4ac862f34ec94850b2adb9bec4a22ed4.uuid='xxxxxxxxxxxxxxxxxxxxxxxxxf0d74f4db340'
passwall.0e75f5dd172d48af9879947bc1cf4a1c.uuid='xxxxxxxxxxxxxxxxxxxxxxxxxf0d74f4db340'
passwall.371ad341853f4c43bc88ff98b6f947b9.uuid='xxxxxxxxxxxxxxxxxxxxxxxxxf0d74f4db340'
passwall.1aa8ca58d3404a36be66797c7d50b6a1.uuid='xxxxxxxxxxxxxxxxxxxxxxxxxf0d74f4db340'
passwall.e656997238a0464283ce81fdf4eb6d8e.uuid='xxxxxxxxxxxxxxxxxxxxxxxxxf0d74f4db340'
passwall.0c85e140636a4614bada023a2e9d2104.uuid='xxxxxxxxxxxxxxxxxxxxxxxxxf0d74f4db340'
passwall.532a4d4e15cd4cdf8c47782a3aae050b.uuid='xxxxxxxxxxxxxxxxxxxxxxxxxf0d74f4db340'
passwall.35c52e18c42b48a382fcf58b914d367a.uuid='xxxxxxxxxxxxxxxxxxxxxxxxxf0d74f4db340'
passwall.b3503f79c3594ed09f928c88edfdd12f.uuid='xxxxxxxxxxxxxxxxxxxxxxxxxf0d74f4db340'
passwall.ade62e70ff4c41e0a76a7abad0b98b4e.uuid='xxxxxxxxxxxxxxxxxxxxxxxxxf0d74f4db340'
passwall.63b5a1aaa2044c0485826412f1e53f3a.uuid='xxxxxxxxxxxxxxxxxxxxxxxxxf0d74f4db340'
passwall.aa89d7a2c6e641e68fa44fd2f62faaa5.uuid='xxxxxxxxxxxxxxxxxxxxxxxxxf0d74f4db340'
passwall.119fc7b51b284613a650db9f6f6d7cac.uuid='xxxxxxxxxxxxxxxxxxxxxxxxxf0d74f4db340'
passwall.fcd6267027e14b03867c1efdf8d2d0f8.uuid='xxxxxxxxxxxxxxxxxxxxxxxxxf0d74f4db340'
passwall.85e78b0956664bfd84c68450e4a0d973.uuid='xxxxxxxxxxxxxxxxxxxxxxxxxf0d74f4db340'
passwall.44521a154f4b47dc80cd1c9c633e2cf4.uuid='xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
passwall.ba94b5833acb44a5b4b25ad7b3da16f7.uuid='xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
passwall.76318dd3216b435bade8567d7f57c5f1.uuid='xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
passwall.4ec448be1c764a009a3ac19137aaa968.uuid='xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
passwall.c332205ddda54628b9a03cc174af33f1.uuid='xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
passwall.8f2f2174b0884901a5e5b31cf358350a.uuid='xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
passwall.24fb3a1ec74c4c30ad48d7ca22bca0b6.uuid='xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'

**Comment by hansyao** [comment]
> 4ee0da30145b40788cac0c919fa66548

你的uci是没有问题的，你把60行删掉，59行不用动就用那个测试的配置，然后运行```./cf_speedtest.sh openwrt```测试下，如果没有问题的话就是你节点配置文件的问题，如果还有问题那就是代码兼容性的问题。

**Comment by wclmgcd** [comment]
已经把60行删掉了的，还是不成功

**Comment by hansyao** [comment]
> 已经把60行删掉了的，还是不成功

passwall 用不了你用clash吧，你那日志不全看不出问题所在的。clash一样的有负载均衡功能。
另外今天刚更新了代码，测速后clash可以直接自动合并现有其他订阅连接了，用起来更方便。按照规则文件CF加速单独分组可按需分流。

**Comment by wclmgcd** [comment]
感谢大佬，K3坏了，现在在N1上运行成功

**Comment by hansyao** [comment]
> 感谢大佬，K3坏了，现在在N1上运行成功

Ok
