### ISSUE TITLE
gist token not found

### ISSUE THREAD

**Issue by Niaber** [hansyao/breakwall#3]
![1](https://user-images.githubusercontent.com/16891707/135043886-d177456d-0ed8-4718-810f-f4c6eea2e894.jpg)
这是怎么回事呢

**Comment by hansyao** [comment]
> ![1](https://user-images.githubusercontent.com/16891707/135043886-d177456d-0ed8-4718-810f-f4c6eea2e894.jpg)
> 这是怎么回事呢

你有参数填得不对吧？

**Comment by hansyao** [comment]
> ![1](https://user-images.githubusercontent.com/16891707/135043886-d177456d-0ed8-4718-810f-f4c6eea2e894.jpg)
> 这是怎么回事呢

这行是你自己改的吧？格式应该是```GIST_TOKEN='你的github token'```, 填得不对肯定报错的

**Comment by Niaber** [comment]
没问题....执行完就还是上传到了gist
