### ISSUE TITLE
【已解决】【bug】已填写gist_token，但是依旧报错：GIST_TOKEN 不存在，请先填入GIST_TOKEN

### ISSUE THREAD

**Issue by Microactive** [hansyao/breakwall#6]
我在阿里云VPS上运行脚本，运行到最后出现以下问题：

""""""""""""""
准备进行规则转换并上传gist
GIST_TOKEN 不存在，请先填入GIST_TOKEN
cat: /tmp/mytemp/gist_response.json: No such file or directory
""""""""""""""

GIST_TOKEN实际上我已经填写，但是填写格式不准确，正确的填写格式不能留空格，应如下：

GIST_TOKEN=xxxxxxxxxxxxxxxxxxxxxxxxxxxxx

**Comment by hansyao** [comment]
可能有两个原因：1.GitHub升级api，原来的代码已不是用，我最近正准备更新下代码用最新的api版本，2.你在阿里云那边服务器连接GitHub不成功
